// <auto-generated />
namespace Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Corrigida_tabela_seguir : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corrigida_tabela_seguir));
        
        string IMigrationMetadata.Id
        {
            get { return "201706082029187_Corrigida_tabela_seguir"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
