// <auto-generated />
namespace Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterada_tabela_seguirs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterada_tabela_seguirs));
        
        string IMigrationMetadata.Id
        {
            get { return "201706082138175_alterada_tabela_seguirs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
